### ISSUE TITLE
codec ES7243 & ES8156 (BSP-236)

### ISSUE THREAD

**Issue by espressif2022** [espressif/esp-bsp#102]
Will the drivers for ES7243 and ES8156 be arranged ？

**Comment by tore-espressif** [comment]
Hi @espressif2022 ,
We don't have the in our current roadmap.

But, drivers for these components are already in esp-adf framework https://github.com/espressif/esp-adf/tree/master/components/audio_hal/driver

Would you like them as separate components? Independent of esp-adf?

**Comment by espressif2022** [comment]
> 

yes, I'd like to.
I'm rearranging the BOX project, ESP32-S3-BOX and ESP32-S3-BOX-Lite share the same repository.

I've delete the old bsp duplicate code, make this driver dependent on the idf_components, now lite lacks these codec components.
It would be better if they also served as separate components.

**Comment by wujiangang** [comment]
> Hi @espressif2022 , We don't have them in our current roadmap.
> 
> But, drivers for these components are already in esp-adf framework https://github.com/espressif/esp-adf/tree/master/components/audio_hal/driver
> 
> Would you like them as separate components? Independent of esp-adf?

I think we need a BSP for esp-box-lite which will depend on es8156, this is exactly the same as the case in the BSP for esp-box, which depends on es8311. So please add this to the roadmap, and share the estimated time of delivery.

**Comment by tore-espressif** [comment]
@wujiangang @espressif2022 We plan to use `esp_codec_dev` component for all our upcoming audio solutions.

You can join out internal discussion in BSP-247
