### ISSUE TITLE
ESP32-S3-Korvo-2: Generic touch controller initialization function is not available (BSP-270)

### ISSUE THREAD

**Issue by TT-Qt** [espressif/esp-bsp#122]
Public function for generic touch controller initialization is not available.

Proposed API-function prototype:
`esp_lcd_touch_handle_t bsp_lcd_touch_init(void);
`

Functionality would be same as in `static lv_indev_t *bsp_display_indev_init(lv_disp_t *disp)` lines 286 - 306 + returning pointer to the touch handle.

https://github.com/espressif/esp-bsp/blob/ee79fd887a1a331bf9eb3935aa0e602780aa80fc/esp32_s3_korvo_2/esp32_s3_korvo_2.c#L286-L306

**Comment by tore-espressif** [comment]
@TTauriainenQt Thanks for the suggestion, makes sense to me.

We plan to add it to a separate header file, so it is clear that the API should be used with custom setups. I'll ping you when the PR is ready
