### ISSUE TITLE
Cannot use display.h from C++ file  (BSP-282)

### ISSUE THREAD

**Issue by TTauriainenQt** [espressif/esp-bsp#144]
https://github.com/espressif/esp-bsp/blob/160c0d66d851c3e247de4c535dc8ddad5a7e585f/esp32_s3_korvo_2/include/bsp/display.h#L42

Suggested fix:
```
#ifdef __cplusplus
extern "C" {
#endif
esp_err_t bsp_display_new(esp_lcd_panel_handle_t *ret_panel, esp_lcd_panel_io_handle_t *ret_io); 
#ifdef __cplusplus
}
#endif
```

**Comment by tore-espressif** [comment]
@TTauriainenQt I'm sorry, I must have missed that. Thanks for the issue?
