### ISSUE TITLE
Display color format / bits per pixel do not have public defines (BSP-283)

### ISSUE THREAD

**Issue by TTauriainenQt** [espressif/esp-bsp#145]
Display color format / bits per pixel is not available from display.h or from esp-bsp.h ( via board specific header ).

In the BSP implementation these values are hardcoded.

Example from Korvo-2 BSP:
https://github.com/espressif/esp-bsp/blob/160c0d66d851c3e247de4c535dc8ddad5a7e585f/esp32_s3_korvo_2/esp32_s3_korvo_2.c#L235-L236

**Comment by tore-espressif** [comment]
@TTauriainenQt yes, these values are constant and specific to the display that is shipped with korvo-2 board. Do you need to change these values?
