### ISSUE TITLE
ESP-BSP allows API-breaking changes for its sub-components (BSP-301)

### ISSUE THREAD

**Issue by TT-Qt** [espressif/esp-bsp#160]
Selecting a specific ESP-BSP version wont protect against API-breaking changes as sub-components are allowed to fetch such changes.

https://github.com/espressif/esp-bsp/blob/bd0efea277b965123ec8252de69d815b21492d4e/esp32_s3_korvo_2/idf_component.yml#L11

**Comment by tore-espressif** [comment]
Hello @TTauriainenQt , we use semantic versioning (major.minor.bugfix) for BSP components, so breaking changes should be introduced only between major versions.

The `^1` syntax allows automatic updates to new versions in this range <1.0.0; 2.0.0), so there should be no breaking change injected into your project. Have you encoutered a situtation where a breaking change was introduced unintentiaonally? We can yank the version and provide a fix.

Anyway, for production code, we recommend fixed versions of _all_ components. For example, although the latest supported version of `esp_lcd_touch_tt21100` by the Korvo2 BSP is 1.0.7 (at the time of writing), you can fix it by adding `espressif/esp_lcd_touch_tt21100: "1.0.5"` to you main `idf_component.yml` file

**Comment by tore-espressif** [comment]
@espzav Seems like your https://github.com/espressif/esp-bsp/pull/150 did not update minimum required version of `esp_lcd_touch` for touch drivers that use the newly introduced API `esp_lcd_touch_register_interrupt_callback`.

Could you please release new versions of affected components? We will then remove the components with invalid dependencies list from IDF component registry, so issues like this one don't repeat.

**Comment by espzav** [comment]
@tore-espressif and @TTauriainenQt I apologize for this issue. Here is the PR with fix: #161

**Comment by tore-espressif** [comment]
#161 is merged and faulty versions removed from component registry.

The issue should be fixed now @TTauriainenQt
