### ISSUE TITLE
How to call the components in the IDF component manager in Arduino? (BSP-303)

### ISSUE THREAD

**Issue by modi12jin** [espressif/esp-bsp#164]
Hello!  I would like to ask how to call the components in the IDF component manager in Arduino?

**Comment by kumekay** [comment]
Hello @modi12jin 

I think the only way now is to use [Arduino as an ESP-IDF component](https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html). It can also be downloaded from the registry: https://components.espressif.com/components/espressif/arduino-esp32

However, in this case, Arduino libraries should be downloaded manually.

We are considering making some Arduino libraries available through the ESP component registry, but I do not have any estimates.
