### ISSUE TITLE
no reset signal on reset pin (BSP-370)

### ISSUE THREAD

**Issue by ZhouKes** [espressif/esp-bsp#211]
no reset signal on reset pin

**Comment by espzav** [comment]
Hello @ZhouKes, please could you provide more details?

**Comment by ZhouKes** [comment]
in components/lcd_touch/esp_lcd_touch_ft5x06/esp_lcd_touch_ft5x06.c， I noticed that the reset pin was initialnized as output ,but no reset pulse was send to the reset pin.

**Comment by espzav** [comment]
@ZhouKes Thank you for reporting the issue. It will be fixed soon. I created pull request with fix here: #216
