### ISSUE TITLE
Compilation error on ESP IDF 5.0.4 (BSP-410)

### ISSUE THREAD

**Issue by valkuc** [espressif/esp-bsp#240]
After merging https://github.com/espressif/esp-bsp/pull/232 I cannot build application on ESP IDF 5.0.4.
Looks like the problem with condition - https://github.com/espressif/esp-bsp/blob/21277f5f1e9103eb2d08e900d410d4c295f98b04/components/lcd/esp_lcd_ili9341/esp_lcd_ili9341.c#L64
The line should be `#if ESP_IDF_VERSION <= ESP_IDF_VERSION_VAL(5, 0, 4)`

@Lzw655 ^

**Comment by tore-espressif** [comment]
@Lzw655 PTAL

**Comment by valkuc** [comment]
Or maybe even better to change that line to:
`#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 1, 0)`

**Comment by igrr** [comment]
This should probably also fix the failing CI job: https://github.com/espressif/esp-bsp/actions/runs/6664742588/job/18112947713.
