### ISSUE TITLE
After ESP-IDF upgrade to 5.1.2 the font isn't loading anymore. (BSP-422)

### ISSUE THREAD

**Issue by Trackhe** [espressif/esp-bsp#259]
After ESP-IDF upgrade to 5.1.2 the font isn't loading anymore.

I used this:
https://docs.lvgl.io/master/overview/font.html
https://lvgl.io/tools/fontconverter
this code:
```
  LV_FONT_DECLARE(font name);
  lv_style_set_text_font(&style, &font name);
```
added the font c file to the Cmakelists.txt and so on

it was working on the older versions but now it dosn't work anymore. if i implement it correctly it seems that the font gets loaded but no font is present on the display. Without the font activated there is font, and on older esp-idf versions like 5.0.0 it is working.

Any idea how i can debug this?

**Comment by Lzw655** [comment]
Hi @Trackhe, did you enable the configuration `LV_USE_LOG` in the menuconfig? And were there any warning or error logs?

**Comment by Trackhe** [comment]
While i was going to activate the log, i also activated the support for subpixel and compressed font sup, and now its working ^^. The change from esp32 to esp32s3 removed the option in the menuconfig and i wasn't remembering that i need that for my font. so thank you for your help ^^.
