### ISSUE TITLE
esp_lcd_touch: Support multiple interfaces to touch controllers (BSP-140)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-bsp#28]
There is one unresolved issue from initial esp_lcd_touch review:

> ... it should have a similar situation to controlled-based LCD panel, where a device might support multiple IO interfaces. We'd better not couple the IO driver inside the device driver.
So to install a touch driver, the step could be (take the I2C as an example):
1. Initialize the I2C bus (in user app)
2. Register an I2C device, get the IO handle
3. Install the touch device with that IO handle, and return the device handle

> It should be possible to use one touch controller with both SPI and I2C.

cc @suda-morris

**Comment by espzav** [comment]
- [ ] Make it compatible with IDF 4.4.2
- [ ] Update BSP and examples for using esp_touch 1.0
