### ISSUE TITLE
esp_lcd_touch_gt911_exit_sleep() INT pin set to output? (BSP-453)

### ISSUE THREAD

**Issue by Reneg973** [espressif/esp-bsp#291]
During initialisation of touch the INT pin is set to input. But on exiting sleep it is set to output. Why is it?

**Comment by espressif2022** [comment]
![企业微信截图_17070514895011](https://github.com/espressif/esp-bsp/assets/111102666/4cd0cd4c-2767-47fd-bff4-f7ebef50ba4b)
Hello, here is the the specs about sleep mode.

**Comment by Reneg973** [comment]
Thank you very much
