### ISSUE TITLE
GSL1680 - Touch Screen Support (IDFGH-12257) (BSP-470)

### ISSUE THREAD

**Issue by rtek1000** [espressif/esp-bsp#305]
### Is your feature request related to a problem?

I'm researching support for SSD1963 (LCD controller with i80 interface) and LVGL. In the same post I also found a touchscreen support reference: "These touch controllers are supported: GT911, TT21100, FT5X06"

- https://github.com/espressif/esp-idf/tree/v5.2/examples/peripherals/lcd/i80_controller

I would like to indicate the possibility of adding support for the GSL1680 touchscreen driver IC (I2C):

- [https://github.com/rtek1000/GSL1680_](https://github.com/rtek1000/GSL1680_)

### Additional context.

https://www.buydisplay.com/5-inch-capacitive-touch-panel-screen-with-controller-gsl1680f

**Comment by VojtechBartoska** [comment]
As mentioned by @suda-morris, we are not able to add support for all 3rd party components. Closing this as wontfix.
