### ISSUE TITLE
PRIV_REQUIRES onewire_bus (BSP-481)

### ISSUE THREAD

**Issue by morgana2313** [espressif/esp-bsp#316]
Using ds18b20  gives an error:

```
components/espressif__ds18b20/src/ds18b20.c:10:10: fatal error: onewire_bus.h: No such file or directory
   10 | #include "onewire_bus.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[...]
BUG: onewire_bus.h found in component espressif__onewire_bus which is already in the requirements list of espressif__ds18b20
```

Fix: components/ds18b20/CMakeLists.txt

```diff
idf_component_register(SRCS "src/ds18b20.c"
                       INCLUDE_DIRS "include"
+                        PRIV_REQUIRES onewire_bus
)
```

**Comment by suda-morris** [comment]
Hi @morgana2313 May I know how you use the onewire_bus and the ds18b20 components? Are you using them with [component manager](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html)? In the manifest file, we have declared the [dependency] (https://github.com/espressif/esp-bsp/blob/master/components/ds18b20/idf_component.yml#L5) on the onewire_bus.

**Comment by tore-espressif** [comment]
Closing due to lack of feedback. Feel free to reopen

**Comment by morgana2313** [comment]
Dank voor uw bericht.

Ik ben afwezig tot 16 juni 2024 en lees sporadisch mijn mail.

Voor dringende zaken kunt u contact opnemen met mijn collega's via 070 891 9 891 of via ***@***.***
