### ISSUE TITLE
M5Stack Core S3 Display up side down (BSP-494)

### ISSUE THREAD

**Issue by limitz** [espressif/esp-bsp#328]
### Board

M5stack Core S3

### Hardware Description

No other hardware

### IDE Name

vi

### Operating System

Linux

### Description

The camera sits below the screen (see https://github.com/espressif/esp-bsp/blob/master/bsp/m5stack_core_s3/README.md)

These lines however put the display upside down:

https://github.com/espressif/esp-bsp/blob/5aedd04f9cd131fad7b77b1a0e202b901c2981a9/bsp/m5stack_core_s3/m5stack_core_s3.c#L412
https://github.com/espressif/esp-bsp/blob/5aedd04f9cd131fad7b77b1a0e202b901c2981a9/bsp/m5stack_core_s3/m5stack_core_s3.c#L413

https://github.com/espressif/esp-bsp/blob/5aedd04f9cd131fad7b77b1a0e202b901c2981a9/bsp/m5stack_core_s3/m5stack_core_s3.c#L448

https://github.com/espressif/esp-bsp/blob/5aedd04f9cd131fad7b77b1a0e202b901c2981a9/bsp/m5stack_core_s3/m5stack_core_s3.c#L449

### Sketch

```cpp
https://github.com/espressif/esp-bsp/tree/master/examples/display
```

### Other Steps to Reproduce

Just tried the example code on the M5Stack Core S3

### I have checked existing issues, README.md and ESP32 Forum

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by espzav** [comment]
@limitz Thank you for this issue. I will fix it.
