### ISSUE TITLE
Link M5 Website/Repo to here (BSP-519)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-bsp#346]
### Describe the solution you'd like

https://github.com/espressif/esp-bsp/tree/master/bsp/m5stack_core_s3

Very cool you do this. 

shouldnt M5 Stack also link here, for all the Folks not wanting to use arduino, so they land here ? 

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by imliubo** [comment]
Hi, thanks for notice, we will add this link to our docs website and each board repo.
And we are doing bsp support for all our board, provide more develop method for more users who use idf.
