### ISSUE TITLE
What hardware board does the `esp_lvgl_port/examples/rgb_lcd` example proj. running on? (BSP-521)

### ISSUE THREAD

**Issue by sonictl** [espressif/esp-bsp#348]
### Related area

component

### Hardware specification

ESP32_with_ILI9341_320x240_TFT_LCD

### Is your feature request related to a problem?

What board does this example i.e. [rgb_lcd](https://github.com/espressif/esp-bsp/tree/master/components/esp_lvgl_port/examples/rgb_lcd) support?

Can I run it on my `ESP32_with_ILI9341_320x240_TFT_LCD` home-made board?

Thank you!

### Describe the solution you'd like

rgb_lcd example to support ILI 9341 LCD screen.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by espzav** [comment]
HI @sonictl,
The RGB LCD example is for screens with RGB interface. The test board is this: https://github.com/espressif/esp-bsp/tree/master/bsp/esp32_s3_lcd_ev_board this example is not for your board. You can use [touchscreen](https://github.com/espressif/esp-bsp/tree/master/components/esp_lvgl_port/examples/touchscreen) example with some modifications. 

OR

Example for ILI9341 320x240 can be used from BSP with [M5Stack CoreS3 board](https://github.com/espressif/esp-bsp/tree/master/bsp/m5stack_core_s3):
1. Use this example: https://github.com/espressif/esp-bsp/tree/master/examples/display
2. Change [dependencies ](https://github.com/espressif/esp-bsp/blob/master/examples/display/main/idf_component.yml) to: `m5stack_core_s3`
3. Compile it:
```
idf.py -D SDKCONFIG_DEFAULTS=sdkconfig.bsp.m5stack_core_s3 -p COMx flash monitor
```
