### ISSUE TITLE
GT911 uses interrupt mode, and most single touches on LVGL are equivalent to two touches. (BSP-523)

### ISSUE THREAD

**Issue by Zmmfly** [espressif/esp-bsp#351]
### Board

Custom board

### Hardware Description

RGB Display with GT911 touch

### IDE Name

VSCode

### Operating System

Windows 11

### Description

LVGL version: `9.1.0`
IDF version: `5.3-rc1`

GT911 uses interrupt mode, expecting a single touch to be effective once; it is actually equivalent to two touches;

It can be determined that it is not a problem with LVGL, related link: https://forum.lvgl.io/t/i-clicked-the-screen-once-but-it-had-the-effect-of-clicking-twice/10848

The problem still exists when the touch point of the touch component is changed to 1 in idf.py menuconfig

### Sketch
like example, only change rst and int pins

```cpp
    esp_lcd_panel_io_i2c_config_t io_config = ESP_LCD_TOUCH_IO_I2C_GT911_CONFIG();

    esp_lcd_touch_io_gt911_config_t tp_gt911_config = {
        .dev_addr = io_config.dev_addr,
    };

    esp_lcd_touch_config_t tp_cfg = {
        .x_max = CONFIG_LCD_HRES,
        .y_max = CONFIG_LCD_VRES,
        .rst_gpio_num = TOUCH_RST_PIN,
        .int_gpio_num = TOUCH_INT_PIN,
        .levels = {
            .reset = 0,
            .interrupt = 0,
        },
        .flags = {
            .swap_xy = 0,
            .mirror_x = 0,
            .mirror_y = 0,
        },
        .driver_data = &tp_gt911_config,
    };

    esp_lcd_touch_handle_t tp;
    esp_lcd_touch_new_i2c_gt911(io_handle, &tp_cfg, &tp);
```

### I have checked existing issues, README.md and ESP32 Forum

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by espzav** [comment]
Hi @Zmmfly, thank you for reporting this issue. We are solving it. It should be solved in this PR: #355
