### ISSUE TITLE
display_lvgl_demos (no Sound / no Audio) (BSP-540)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-bsp#376]
### Board

ESP-BOX-3

### Hardware Description

ESP-BOX-3

### IDE Name

none

### Operating System

Linux

### Description

https://github.com/espressif/esp-bsp/tree/master/examples/display_lvgl_demos
no Audio.
Tested on a M5Stack S3 and on a ESP-BOX-3 no Sound. 

### Sketch

```cpp
https://espressif.github.io/esp-launchpad/?flashConfigURL=https://espressif.github.io/esp-bsp/config.toml&app=display_lvgl_demos
```

### I have checked existing issues, README.md and ESP32 Forum

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by tore-espressif** [comment]
Hello @diplfranzhoepfinger this example does not have audio implemented. It is only graphical demos from https://github.com/lvgl/lvgl ported to ESP boards.

This example should have audio working https://github.com/espressif/esp-bsp/tree/master/examples/display_audio_photo but we have some bug reports for esp-idf master branch that we are trying to solve now
