### ISSUE TITLE
LVGL: Garbled output on esps2 mini with OLED

### ISSUE THREAD

**Issue by mado89** [espressif/esp-bsp#398]
### Board

ESP32 S2 Mini

### Hardware Description

ESP32 S2 Mini board with an OLED display 
![Display](https://github.com/user-attachments/assets/34301923-58a8-4d75-bcc1-641b7d36555f)

### IDE Name

VSCode

### Operating System

Ubuntu

### Description

When using the i2c_oled_example from the examples directory the display does not show a text but only moving pixels as shown in the attached image. The setup works when running other display code.
![GarbeledOutput](https://github.com/user-attachments/assets/730c2a2b-94a6-4452-ab7a-227f25edb0fd)

### Sketch

```cpp
I2C_oled_example_main.c from the examples directory

idf_component.yml:
## IDF Component Manager Manifest File
dependencies:
  lvgl/lvgl: "^9.2.0"
  espressif/esp_lvgl_port: "^2.3.0"
  esp_lcd_sh1107: "^1"
  ## Required IDF version
  idf:
    version: ">=4.1.0"
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies `public` flag can be set.
  #   # `public` flag doesn't have an effect dependencies of the `main` component.
  #   # All dependencies of `main` are public by default.
  #   public: true
```

### I have checked existing issues, README.md and ESP32 Forum

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by espzav** [comment]
Hello @mado89, This example was mainly for LVGL8. We found the issue, when it is used with LVGL9. We have pull request here, which should solve the issue: https://github.com/espressif/esp-bsp/pull/392 There is readme, how to do it.

**Comment by mado89** [comment]
@espzav I will give this example another try with a clean source tree and report back

**Comment by mado89** [comment]
@espzav Happy to report that it now works.

**Comment by espzav** [comment]
@mado89 Yes, you can close the issue.
