### ISSUE TITLE
TCA9554 driver using ESP driver/i2c_master component (BSP-561)

### ISSUE THREAD

**Issue by karunt** [espressif/esp-bsp#402]
### Related area

Driver

### Hardware specification

Support for Qualia ESP32-S3

### Is your feature request related to a problem?

Espressif is deprecating the driver/i2c component and is encouraging using the driver/i2c_master component instead.

### Describe the solution you'd like

The TCA9554 driver component for ESP-IDF development uses the driver/i2c component. Is the TCA9554 component being upgraded to use the new driver/i2c_master component?

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by tore-espressif** [comment]
Will be fixed by https://github.com/espressif/esp-bsp/pull/424
