### ISSUE TITLE
[esp32-p4] hdmi extension board (BSP-565)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-bsp#411]
Hello espressif team.
I would like to thank you for sample board of hdmi extension. It is working great.
So far i did just quick test with 2 examples, display lvgl and `display_usb_hid` and it works as expected.

If you have ideas how i can help you testing it please let me know.

Thanks

**Comment by espzav** [comment]
Hello, we released the HDMI support in latest BSP for ESP32-P4 some days ago. Now, you can use latest version. There are supported many resolutions up to 720p. Unfortunatelly 1080p cannot be support with our hardware. Maximum is 1920x1080 30Hz (it is not supported with many monitors and TVs). 

Now, I am closing this "issue". Fell free to reopen, if you will have any questions.
