### ISSUE TITLE
Add method to request multiple framebuffers on noglib version (BSP-566)

### ISSUE THREAD

**Issue by Spritetm** [espressif/esp-bsp#412]
### Related area

Display

### Hardware specification

BSP package P4-ev-board

### Is your feature request related to a problem?

For a game port, I need multiple framebuffers I can draw to. The LVGL version of the BSP allows me to select that, but in noglib, there is no way to get more than 1 framebuffer

### Describe the solution you'd like

bsp_display_config_t could get a flag or integer field indicating multiple framebuffers are requested; bsp_display_new would need to honour that.

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by espzav** [comment]
You can select it in menuconfig:
![image](https://github.com/user-attachments/assets/56af73b5-b395-4c72-8277-3e17cdaaab69)

**Comment by Spritetm** [comment]
@espzav I don't think so. I can't really see where that option comes from in your screenshot (current bsp code only has that option in [bsp/esp32_s3_lcd_ev_board/Kconfig](https://github.com/espressif/esp-bsp/blob/9e3665fa1cb469cc84b23044e3e394e068831f7e/bsp/esp32_s3_lcd_ev_board/Kconfig#L81), but and the option there is CONFIG_BSP_DISPLAY_LVGL_AVOID_TEAR=y which as the name suggests is an option that involves LVGL. As mentioned before, I'm specifically using the noglib version of the BSP, which does not use or rely on LVGL.

**Comment by espzav** [comment]
@Spritetm Oh sorry, it will be added in this PR: https://github.com/espressif/esp-bsp/pull/401 and it is not merged yet. It will be merged soon (I hope today). I think that this option should be there for noglib too.

**Comment by espzav** [comment]
@Spritetm The mentioned PR was merged today. Is it ok? Can we close this issue?

**Comment by espzav** [comment]
I am closing this issue. If you have any more questions, feel free to reopen it.
