### ISSUE TITLE
Fix format warnings (BSP-175)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-bsp#50]
esp-idf is changin defintion of `uint32_t` from unsigned int to unsigned long.
Now we need to use PRIx32 specifier from inttypes.h instead of d or u, during print.

TODO:

- [x] Remove -Wno-format compiler option
- [x] Fix all format warings

**Comment by tore-espressif** [comment]
Identified external dependencies: 
* https://github.com/espressif/esp32-camera

**Comment by tore-espressif** [comment]
Hi @chmorgan , I think this migration guide sums it up pretty well: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#espressif-toolchain-changes
PTAL!

**Comment by chmorgan** [comment]
Ahh, so its driven by upstream changes... makes sense
