### ISSUE TITLE
how to use example in espidf4.4？ (BSP-201)

### ISSUE THREAD

**Issue by fireflylr** [espressif/esp-bsp#68]
I want to use these examples, but am I reporting a mistake in the build project, the current version can only run on the idf5 version? I am currently using idf4.4, how should I deal with this problem, I do not know in which branch is corresponding to the support of idf4.4, please let me know, thank you

**Comment by tore-espressif** [comment]
What exactly do you mean by blank? Does the LCD backlight work?

**Comment by tore-espressif** [comment]
Hello @fireflylr thank you for your patience.

I don't have access to the board as of now. I'll try it next week. Thank you!

**Comment by tore-espressif** [comment]
@fireflylr Could you please double check that:
1. your board is Kaluga-ki v1.3
2. That you have the 3.2inch display connected? (see attached picture)
3. All microswithces (on both the main and LCD board) are set as in the attached picture?

![20221124_125020](https://user-images.githubusercontent.com/77206109/203778642-493124bb-96b0-4f52-be64-96a9dba5c397.jpg)
![20221124_124826](https://user-images.githubusercontent.com/77206109/203778645-12049b45-70bc-4ff4-a25d-1eed2db9d243.jpg)

![20221124_124840](https://user-images.githubusercontent.com/77206109/203778635-0a4ceb13-a254-401e-9004-95c20a761e1c.jpg)

**Comment by travisjayday** [comment]
Same issue here. IDF 5.0, kaluga 1.3, blank ( white ) LCD

**Comment by tore-espressif** [comment]
I could not reproduce the problem on my Kaluga. I'll try on different boards, just to make sure

**Comment by tore-espressif** [comment]
@fireflylr @travisjayday I can see similar issues on different boards. Unfortunately, we shipped Kaluga-kits with different LCD subboards. Could you please try the following:
1. Slow down SPI clock to 40MHz https://github.com/espressif/esp-bsp/blob/master/esp32_s2_kaluga_kit/include/bsp/esp32_s2_kaluga_kit.h#L252
2. In case you screen is black (on LCD board version 1.1) you need to drive GPIO6 low, to enable the backlight

**Comment by travisjayday** [comment]
Hello @tore-espressif, I can confirm it works now with IDF 5.0 after switching SPI clcok to 40MHz as you described in step 1. Thank you.
