### ISSUE TITLE
A little question about esp_lcd_touch components (BSP-212)

### ISSUE THREAD

**Issue by Lzw655** [espressif/esp-bsp#77]
@espzav Hi Vilem, I have a little confused with the 120th line below. I think it should be like ``*swap = tp->config.flags.swap_xy;``. And there are also two more functions (`esp_lcd_touch_get_mirror_x/y`) like that.
https://github.com/espressif/esp-bsp/blob/1214641525e3e9018d5826a64cd1147c246bdef2/components/lcd_touch/esp_lcd_touch/esp_lcd_touch.c#L112-L124

**Comment by espzav** [comment]
@Lzw655 Oh, so sorry. It is bad. Thank you for reporting this issue. I will fix it.

**Comment by Lzw655** [comment]
So fast!
