### ISSUE TITLE
Minor updates on the structure of SquareLine Studio boards (BSP-213)

### ISSUE THREAD

**Issue by kisvegabor** [espressif/esp-bsp#80]
Hi,

We made a few little modification on directory structure of the boards in SquareLine Studio. The current version is also working but maybe you want to make the content of the `espressif` folder aligned with the other board folders. We manually updated the name of all existing boards and files and this is how it looks like now:
```shell
├── arduino
│   ├── tft_espi_v1_0_0
│   │   ├── tft_espi.png
│   │   ├── tft_espi.slb
│   │   └── tft_espi.zip
│   └── tft_espi_v1_0_1
│       ├── tft_espi.png
│       ├── tft_espi.slb
│       └── tft_espi.zip
├── desktop
│   ├── eclipse_sdl_v1_0_0
│   │   ├── eclipse_sdl.png
│   │   ├── eclipse_sdl.slb
│   │   └── eclipse_sdl.zip
│   ├── eclipse_sdl_v1_0_1
│   │   ├── eclipse_sdl.png
│   │   ├── eclipse_sdl.slb
│   │   └── eclipse_sdl.zip
│   ├── micropython_v1_0_0
│   │   ├── micropython.png
│   │   ├── micropython.slb
│   │   └── micropython.zip
│   └── micropython_v1_0_1
│       ├── micropython.png
│       ├── micropython.slb
│       └── micropython.zip
└── espressif
    ├── espbox_v1_0_0
    │   ├── espbox.png
    │   ├── espbox.slb
    │   └── espbox.zip
    └── espwroverkit_v1_0_0
        ├── espwroverkit.png
        ├── espwroverkit.slb
        └── espwroverkit.zip
```

So `<vendor>/<board_name>_<version>/<files_without_version>`. 

---
We also needed to update how LVGL versions are enumerated in the `.slb` file. Our initial idea was to support wildchars like `v8.0+` but finally we have choosen a more explicit way. So the supported LVGL versions needs to be written one by one like: 
```
"supported_lvgl_version": "8.2.0, 8.3.3",
```
(At this moment we support these 2 LVGL versions)

---

If you wish I can send a PR for `gen.py`, but I don't know if LVGL v8.3.3 is supported.

**Comment by espzav** [comment]
@kisvegabor Thank you for informing us about changes. I created a pull request with generator changes.
