### ISSUE TITLE
error: unknown type name 'portMUX_TYPE' (BSP-217)

### ISSUE THREAD

**Issue by Lzw655** [espressif/esp-bsp#87]
@espzav Hi, when I didn't declare `esp_lcd_touch.h` before `freertos/FreeRTOS.h` and `freertos/semphr.h`, I got an error as belows:
```
error: unknown type name 'portMUX_TYPE'
   69 |     portMUX_TYPE lock; /*!< Lock for read/write */
      |     ^~~~~~~~~~~~
```
I think maybe it's better to include `freertos/FreeRTOS.h` and `freertos/semphr.h` in the file `esp_lcd_touch.h`.

**Comment by AI-Tipto** [comment]
same error!

/managed_components/espressif__esp_lcd_touch/include/esp_lcd_touch.h:69:5: error: 'portMUX_TYPE' does not name a type; did you mean 'portBASE_TYPE'?
   69 |     portMUX_TYPE lock; /*!< Lock for read/write */
      |     ^~~~~~~~~~~~
      |     portBASE_TYPE
In file included from /Users/asura/app/Esp32s3/LvglUI/managed_components/lvgl__lvgl/src/core/lv_obj.h:140,

**Comment by espzav** [comment]
Fixed and merged on master.
